# Generated by Django 5.1.7 on 2025-03-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('release_year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('genres', models.CharField(choices=[('Action', 'Боевик'), ('Comedy', 'Комедия'), ('Drama', 'Драма'), ('Fantasy', 'Фэнтези'), ('Horror', 'Ужасы'), ('Mystery', 'Мистика'), ('Romance', 'Романтика'), ('Sci-Fi', 'Научная фантастика'), ('Thriller', 'Триллер'), ('Animation', 'Анимация'), ('Documentary', 'Документальный')], max_length=255, verbose_name='Жанр')),
                ('director', models.CharField(blank=True, max_length=255, verbose_name='Режиссер')),
            ],
        ),
    ]
