# Generated by Django 5.1.7 on 2025-03-06 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', '👍 Нравится'), ('funny', '🤣 Смешно'), ('love', '😍 Обожаю'), ('sad', '😢 Грустно'), ('shocked', '😱 Шок'), ('mindblown', '🤯 Взрыв мозга'), ('respect', '\U0001fae1 Уважение'), ('dislike', '👎 Не нравится'), ('clown', '🤡 Клоун'), ('poop', '💩 Полный отстой'), ('heart', '❤️ Любовь'), ('thinking', '🤔 Думаю'), ('angry', '😡 Злюсь'), ('fire', '🔥 Огонь'), ('ghost', '👻 Жутко')], max_length=10, verbose_name='Реакция')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='movies_collection.movie', verbose_name='Фильм')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
            },
        ),
    ]
