# Generated by Django 5.1.7 on 2025-03-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_collection', '0005_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.TextField(verbose_name='Жанры'),
        ),
    ]
