# Generated by Django 5.1.7 on 2025-03-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_collection', '0007_rename_release_year_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='en_title',
            field=models.CharField(default='', max_length=255, verbose_name='Оригинальное название'),
            preserve_default=False,
        ),
    ]
