# Generated by Django 5.1.7 on 2025-03-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_collection', '0008_movie_en_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='en_title',
        ),
    ]
