# Generated by Django 5.1.7 on 2025-03-12 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_collection', '0009_remove_movie_en_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('user', 'movie', 'reaction'), name='unique_user_movie_reaction'),
        ),
    ]
