# Generated by Django 5.1.7 on 2025-03-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_collection', '0010_reaction_unique_user_movie_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(max_length=255, verbose_name='Название'),
        ),
    ]
